### ISSUE TITLE
Add JS binding

### ISSUE THREAD

**Issue by Andrey1994** [brainflow-dev/brainflow#123]

**Comment by dman2210** [comment]
bump

**Comment by GordonPmnt** [comment]
Hello guys,

I started working on it locally. Keep you posted

**Comment by GordonPmnt** [comment]
Is there any kanban view or board somewhere? I'd like to put this in progress.

Already wrotte a pretty important part of the board-shim. My goal is to do it by the end of the year (cannot go very quick because I don't have much time), but definitely doing it.

Should I open a wip PR somewhere to show progress?

**Comment by Andrey1994** [comment]
Wip pr will be good also I will be able to help then.

And we have no boards to track tasks

**Comment by dman2210** [comment]
I might be able to pitch in here. Any progress?

**Comment by GordonPmnt** [comment]
> I might be able to pitch in here. Any progress?

Actually yes @dman2210 . I did a good part of the board-shim and I started the data-filters.

I'm going to create a PR but for this I firstly need to find a good example to create a TS and JS package for brainflow. I'm not the king of webpack so I postponed a bit. If you have any available boilerplate, might help actually.

Here is a screenshot of a test I did with electron.js. Started a session with synthetic board, recorded 5 secs and did log the first channel. 
![image](https://github.com/brainflow-dev/brainflow/assets/46138784/a00155c0-7716-40a4-9670-f4edff7d7e97)

**Comment by dman2210** [comment]
Is webpack necessary?

If so I am told these are good biolerplates to pull from for javascript webpack.
https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/prod.config.js
https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/examples/webpack-plugin-serve/webpack.config.js

Here are some package.json files as well for javascript.

https://github.com/erikras/react-redux-universal-hot-example/blob/master/package.json
https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/package.json
https://github.com/firebase/firebase-js-sdk/blob/master/packages/app/package.json

This article had a very simple one for typescript.

https://blog.logrocket.com/using-webpack-typescript/

**Comment by GordonPmnt** [comment]
Hello @dman2210 @Andrey1994 

This is here, I did put an example with the boardshim class: https://github.com/brainflow-dev/brainflow/pull/646/files

Right now, you can try it running the command `yarn run example` 
(you'll have to copy paste yourself the dll file in the lib repo though. I haven't updated any scripts yet.

**Comment by Andrey1994** [comment]
Hi @GordonPmnt! Great progress, I will take a look
