### ISSUE TITLE
Setup autogenerated API reference for Matlab and Julia

### ISSUE THREAD

**Issue by Andrey1994** [brainflow-dev/brainflow#145]

**Comment by matthijscox** [comment]
https://github.com/JuliaDocs/Documenter.jl can set up automated API references from Julia docstrings. 

We can probably use that. Don't know yet how to integrate that with pandoc.

**Comment by Andrey1994** [comment]
Readthedocs uses sphinx, so probably we need this https://github.com/bastikr/sphinx-julia

I've tried smth but dont remember what exactlyand why it didnt work

**Comment by Andrey1994** [comment]
https://brainflow.readthedocs.io/en/stable/BrainFlowDev.html#instructions-to-build-docs-locally

**Comment by Andrey1994** [comment]
done for matlab, impossible for julia right not
