### ISSUE TITLE
Occasional MacOSX CI Failures

### ISSUE THREAD

**Issue by xloem** [brainflow-dev/brainflow#240]
I haven't found the cause of any of these quite yet.  I pursued them for a couple days, but I am not presently working on them.  I don't personally have a macosx system to test on.  That could change some day.  I'll edit this post to list them below as I bump into them.
- [ ] The Fascia Python Markers test has rarely segfaulted for me on github's servers without any diagnostic output: https://github.com/brainflow-dev/brainflow/runs/1942729201#step:34:35 .  Return code -11 indicates segfault.
- [ ] After maybe 100 runs I had a strange error in the EEG Metrics test: https://github.com/xloem/brainflow/runs/1951896447#step:58:13

Ideas for debugging this:
- [X] Making a branch with many copies of the macosx workflow and other workflows removed can help make the issue more reliable to reproduce, but it is very slow to wait for all the runs: https://github.com/xloem/brainflow/pull/6
- [ ] There is a tmate github action which allows shell access to github workflows.  The login information is shown in the workflow log console output.  https://github.com/xloem/brainflow/pull/6/commits/df8a7d8ad391d878bc59a051b08f81606e52a5ce
- [ ] libsegfault can display a strack trace when segfaults happen.  I added it to that branch, but I haven't gotten its dependency, libunwind, to be recognised on the macosx system yet.  The tmate action can probably help that a lot.

**Comment by Andrey1994** [comment]
fascia is in wip stage(as a device), some tests for it were disabled in CI but looks like one of them was not. I fixed it
