### ISSUE TITLE
referring to the locked issue 246

### ISSUE THREAD

**Issue by dmedine** [brainflow-dev/brainflow#252]
It seems like we are starting to be on the same page, which is very good.

From https://github.com/brainflow-dev/brainflow/issues/246

> There is no way to handle it in BrainFlow, I never made statements that BrainFlow supports it. And more likely will never do because its not designed for it.|
It should be done by library like LSL or using custom solution based on zeromq for example running on top of BrainFlow.

This is precisely my point. There is no 'LSL vs. BrainFlow'. There is LSL and there is BrainFlow. And there _should_ be LSL + BrainFlow! 

Actually, I'm not sure there is much work for either team to do there, since both support basically the same set of languages already anyway.

**Comment by dioptre** [comment]
It would be interesting to see LSL in Brainflow to demonstrate the difference in adding the middleman.
