### ISSUE TITLE
Replace error code with error enum string

### ISSUE THREAD

**Issue by matthijscox** [brainflow-dev/brainflow#274]
A small task I always forget, but would like:

`ERROR: BrainFlow.BrainFlowError("Error in start_stream 18", 18)`
I'd prefer to see instead:
`ERROR: BrainFlow.BrainFlowError("Error in start_stream SYNC_TIMEOUT_ERROR", 18)`

**Comment by Andrey1994** [comment]
Yeah, it would be good.

Its done for python and some other languages but not for all of them
