### ISSUE TITLE
How to use Brainflow with custom hardware

### ISSUE THREAD

**Issue by ut33** [brainflow-dev/brainflow#300]
I've working on a custom signal acquisition board and I would like to use Brainflow to stream data from python, what should I do?
Thanks in advance

**Comment by Andrey1994** [comment]
Hi, here is a guide how to add new boards https://brainflow.readthedocs.io/en/stable/BrainFlowDev.html#instructions-to-add-new-boards-to-brainflow 
If you have questions about adding feel free to ask

**Comment by ut33** [comment]
Hi,
My board has a sampling rate of 1000 sps and 32 channels, so every
millisecond it gets 32 data points and every second it has 32000 data
points. Will brainflow be able to plot and record this data in real time?
Best Regards,
Vini

**Comment by ut33** [comment]
Thank you for your response.
My board has a sampling rate of 1000 sps and 32 channels, so every
millisecond it gets 32 data points and every second it has 32000 data
points. Will brainflow be able to record this data in real time?
Best Regards,
Vini
