### ISSUE TITLE
Add EmotiBit devices

### ISSUE THREAD

**Issue by Andrey1994** [brainflow-dev/brainflow#331]
https://www.emotibit.com/

**Comment by mesca** [comment]
I will be happy to test and provide feedback.

**Comment by matthijscox** [comment]
Cool, seems there is code available here for reference or reuse: https://github.com/EmotiBit/ofxEmotiBit. 

We just need a good c++ dev now (I should really improve my skills :p). Generally it is Andrey doing the work.

I recall Andrey mentioned that the output data format of the emotibit can be changed flexibly and that this may be the primary challenge for BrainFlow integration.

**Comment by mesca** [comment]
I think there is some work to be done on the firmware before that.
