### ISSUE TITLE
Add example of OpenBCI Bluetooth connection

### ISSUE THREAD

**Issue by hack-r** [brainflow-dev/brainflow#340]
The OpenBCI part of the docs only really covers serial connections well. Since both Ganglion and Cyton have bluetooth (BLE) an example of how to run an example like `get_data.py` with bluetooth would be very useful.

I'm trying to use brainHat as a stop gap. It makes the bluetooth connection and streams data for LSL and brainflow over a local IP and port. Even so, I must be unclear on the connection format...

For example 

`python3 ~/Documents/brainflow_examples/get_data.py --ip-address 227.1.1.1 --ip-port 6677 --board-id 0`

leads to

```
    raise BrainFlowError('unable to prepare streaming session', res)
brainflow.board_shim.BrainFlowError: INVALID_ARGUMENTS_ERROR:13 unable to prepare streaming session
```

**Comment by Andrey1994** [comment]
Ganglion and Cyton both need a dongle to get data, raw BLE connection is not supported. (only via COM port from the dongle), arguments needed for cyton and ganglion can be found here https://brainflow.readthedocs.io/en/stable/SupportedBoards.html
