### ISSUE TITLE
Difficulty installing the MATLAB

### ISSUE THREAD

**Issue by masteroforest** [brainflow-dev/brainflow#35]
Good afternoon.
The instructions say "Add folders lib and inc to Matlab path". Only these directories are missing in brainflow / matlab-package / brainflow. And without their indication, an error occurs. Tell me, please, where are folders lib and inc located?

**Comment by Andrey1994** [comment]
These folders will be created as soon as you compile core module, instructions to compile it https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#compilation-of-core-module-and-c-binding

**Comment by masteroforest** [comment]
Thank.
