### ISSUE TITLE
Jetson Nano: OSError

### ISSUE THREAD

**Issue by madhavgovindgmg** [brainflow-dev/brainflow#354]
Hey!
I ran into a problem: On using BrainFlow on Jetson Nano Device it comes up with this error.

**OSError: /home/bme/.local/lib/python3.6/site-packages/brainflow/lib/libBoardController.so: cannot open shared object file: No such file or directory**

I am running the script from the [code samples](https://brainflow.readthedocs.io/en/stable/Examples.html#python-get-data-from-a-board).

![BRAINFLOW ERROR](https://user-images.githubusercontent.com/91531494/135060511-5457060b-f51b-4a54-bc5b-22238ee2f889.png)

**Comment by Andrey1994** [comment]
Hi, make sure that you've compiled C++ code before installation of python package. https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#linux

After that run `sudo python -m pip install -U .` from python-package folder

**Comment by Andrey1994** [comment]
Also, if you have ANT Neuro board it will not work on Jetson Nano, because for ANT Neuro we need to use SDK provided by ANT Neuro company as a precompiled library(we have no source code) and they haven't built it for ARM(only for x86)
