### ISSUE TITLE
Check that Muse works after firmware update

### ISSUE THREAD

**Issue by Andrey1994** [brainflow-dev/brainflow#398]
Maybe `write_command` should be used instead `write_request`. If so, we need to get firmware version in `prepare_session` method

**Comment by Andrey1994** [comment]
just realized, we cannot get fw version because we need to send a command for it and if the way we send commands to device depends on firmware we cannot do it programmatically

**Comment by Andrey1994** [comment]
Tested with 1.0.6 version and it works wo any changes(tested on macos 10.15 and windows 11), if more people complain about ubuntu maybe will add ubuntu specific handling

**Comment by Zibri** [comment]
off topic: does anybody know if there is a repository somewhere for MUSE firmwares?

**Comment by Andrey1994** [comment]
I believe its private

**Comment by Zibri** [comment]
> I believe its private

probably, but the MUSE 2 is "obsolete" and perhaps someone saved it.
