### ISSUE TITLE
Brainflow not compiling with rust bindgen

### ISSUE THREAD

**Issue by AmirGh1712** [brainflow-dev/brainflow#404]
I am trying to use brainflow as part of a rust codebase using FFI.
When rust's bindgen (https://github.com/rust-lang/rust-bindgen) tries to compile the brainflow code with clang it fails with redefinition errors like:
/brainflow-a96e957ebeac204e/out/inc/brainflow_input_params.h:6:12: error: redefinition of 'IpProtocolType'
It's unclear why that happens but it seems that the compiler is ignoring the pragma once flag.
Replacing the pragma once with ifndef fixes this issue and seems to be the recommended way to handle redefinition checks (since pragma once is not standard and not all compilers accept it).
I've attached the python script I've written to replace all the pragma once with ifndef. Perhaps you want to consider adding it into the brainflow codebase?
Maybe you've encountered this issue before and have another solution?

[replace.txt](https://github.com/brainflow-dev/brainflow/files/7776787/replace.txt)

**Comment by Andrey1994** [comment]
Hi, thanks! 
We have binding for rust which works and we also have tests for it. https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#rust 

I've never seen issues with pragma once and I think it's almost a standard(https://en.wikipedia.org/wiki/Pragma_once)
![image](https://user-images.githubusercontent.com/8217521/147408265-191ef1cd-9920-4ed7-b79c-207406b8d32a.png)
