### ISSUE TITLE
A detailed tutorial of windows configuration environment is suggested

### ISSUE THREAD

**Issue by aimzs** [brainflow-dev/brainflow#425]
I want to know the detailed tutorial of using cmake in Windows configuration for C + + binding；
Including the detailed configuration above.

Is Cmake directly under the root directory？
I tried for a long time without success

**Comment by aimzs** [comment]
The main reason is that brianflow cannot be found in cmakelist in test
![image](https://user-images.githubusercontent.com/59354826/158946640-2e158c83-ef2a-4ccc-af2f-b0f09337bbc4.png)
find_package (
    brainflow CONFIG REQUIRED
)

**Comment by Andrey1994** [comment]
Hi,

https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#compilation-of-core-module-and-c-binding

It prints exact cmake commands, you can run it and check the output

**Comment by Andrey1994** [comment]
Or check the source code of build.py

**Comment by aimzs** [comment]
I already checked  the source code of build.py.  
i have a problem for cpp test.

**Comment by Andrey1994** [comment]
Check this https://brainflow.readthedocs.io/en/stable/Examples.html#id1

**Comment by Andrey1994** [comment]
For windows its almost the same

**Comment by Andrey1994** [comment]
https://github.com/brainflow-dev/brainflow/blob/master/.github/workflows/run_windows.yml#L95 example from ci

**Comment by aimzs** [comment]
ok,i want to try. thanks
