### ISSUE TITLE
Unable to build core.

### ISSUE THREAD

**Issue by masteroforest** [brainflow-dev/brainflow#45]
Hello! I tried several options for building the kernel ... 
1) Using Visual Studio 2019: changed the build_win64.cmd ("cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=..\\installed64 .. ") and launched it. Then I tried to open CmakeLists.txt from Visual Studio and compile a project on it.
2) Installed the Visual Studio 2017: launched an unchanged build_win64.cmd (from tools). Then I tried to open CmakeLists.txt from Visual Studio and compile a project on it.
Of course, cmake is installed, in all cases it started GUI first to check the equipment. I tried to build a kernel with both connected and disconnected boards(Cyton&Daisy). Screenshots below. Tell me, please, in how to assemble the core after all?

![BF_1](https://user-images.githubusercontent.com/31575787/82122285-58936080-979b-11ea-9145-b4d390cd4817.jpg)
![BF_2](https://user-images.githubusercontent.com/31575787/82122286-59c48d80-979b-11ea-930e-03261a42cfd9.jpg)
![BF_3](https://user-images.githubusercontent.com/31575787/82122287-5b8e5100-979b-11ea-8ca0-c224acb8ba22.jpg)

**Comment by Andrey1994** [comment]
You need to do exactly whats written in docs and what I wrote in previous issues. You even dont need to launch visual studio.

Just open command line on windows, go to brainflow's folder and run tools\build_win64.cmd
![image](https://user-images.githubusercontent.com/8217521/82124256-71554380-97a6-11ea-9b0f-514e42d9edc8.png)

In the end you will see this:
![image](https://user-images.githubusercontent.com/8217521/82124298-d27d1700-97a6-11ea-9637-884e45305222.png)

Thats all, core module is compiled and installed.

If you need Matlab binding you will see that now there are folders inc and lib in brainflow/matlab-binding/brainflow. 
https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#matlab

**Comment by masteroforest** [comment]
Thank! The kernel has compiled. True, the file (build_win64.cmd) with the edits you specified moved to the root of the brainflow. Otherwise, the file could not find the CmakeLists.txt.
