### ISSUE TITLE
Stream Muse 5th (AUX) EEG Channels

### ISSUE THREAD

**Issue by JohnGriffiths** [brainflow-dev/brainflow#504]
**Use case:**

All three muse devices allow for a micro-USB connection input, which can be fruitfully used for an additional EEG channel, such as at Oz (visual) or Cz (central). This channel is also extremely useful for quantifying bluetooth lags and synchronization, as it can receive a direct trigger input defining e.g. a stimulus onset, that is approximately synchronized with the arrival of that stimulus (i.e. a picture or sound played/displayed on computer) at the eyes/ears. 

BlueMuse seems to have this figured out, although I don't understand the finer details

e.g. 
https://github.com/kowalej/BlueMuse/pull/49/files

**Describe the solution you'd like:**
Brainflow muse EEG returns 5 channels, not 4. 

**Describe alternatives you've considered:**
Using bluemuse is currently the only alternative I know of. I like bluemuse but I prefer brainflow.

**Comment by Andrey1994** [comment]
I will take a look, could you tell how to test it properly and which hardware needed? And how to connect it? Ideally I would like to test it wo buying new hardware

**Comment by JohnGriffiths** [comment]
If you install and run bluemuse you should get an lsl stream of the aux chan for any muse device

https://github.com/kowalej/BlueMuse

Is that what you're asking for re: testing?

Perhaps it's overly naive but I would assume it's just a case of adding another peripheral function as with the other chans

https://github.com/brainflow-dev/brainflow/blob/f9c08dd76bb74df38e88fe11bdbf82fdaba5ddb9/src/board_controller/muse/muse.cpp#L15 

and seeing if you get data from it.
