### ISSUE TITLE
[Java] Can there be a solution that is better than `BoardShim.unpack_from_jar`?

### ISSUE THREAD

**Issue by mgroth0** [brainflow-dev/brainflow#517]
It is not ideal that .dylib files are appearing in the project folder on `gradle run`. Can there be an option to use another location?

[This doc](https://java-native-access.github.io/jna/4.2.1/com/sun/jna/NativeLibrary.html#library_search_paths) gives some useful information for different places that these files can be. "Context class loader classpath" seems like a good option.

**Comment by Andrey1994** [comment]
Hi, idk, I didnt find a better option when I was writting it.
If context loader classpath works for you feel free to send a PR, it will be great. Another approach to try can be to change env variables

**Comment by Andrey1994** [comment]
you need to compile it first using build.py https://brainflow.readthedocs.io/en/stable/BuildBrainFlow.html#compilation-of-core-module-and-c-binding 

And as far as I understand you need to copy files to subfolder like linux-x64, etc https://github.com/brainflow-dev/brainflow/blob/master/java_package/brainflow/pom.xml#L50. Maybe you will need to change files like build.cmake(there are a lot of them, you probably need to run smth like `find . -name build.cmake` https://github.com/brainflow-dev/brainflow/blob/master/src/board_controller/build.cmake#L172

**Comment by Andrey1994** [comment]
Also, when you compile it locally you do it only for one OS, while in jar file for releases there are libs for all OSes so this jar is x-platform. Its done by this CI job https://github.com/brainflow-dev/brainflow/blob/master/.github/workflows/deploy.yml, it copies files for all OSes from AWS

**Comment by Andrey1994** [comment]
completed
