### ISSUE TITLE
Intermittent streaming error

### ISSUE THREAD

**Issue by danielemarinazzo** [brainflow-dev/brainflow#529]
Every now and then I get an error, see this issue (also including system info and case study)

https://github.com/NeuroTechX/eeg-notebooks/issues/191#issue-1285570447

thanks!

**Comment by Andrey1994** [comment]
Hi, you should reproduce it using simple brainflow example and using the latest version. Then I will take a look

Recently there was a release with fixes for muse and I belive eeg notebooks not updated yet to use it. Also, simple examples are easier for debugging

**Comment by Andrey1994** [comment]
Closing for now, feel free to reopen if you see this issue using smth like brainflow_get_data.py from examples and 5.1.0+ version
