### ISSUE TITLE
Sync BoardShim.start_stream and BoardShim.add_streamer

### ISSUE THREAD

**Issue by isaacplotkin** [brainflow-dev/brainflow#563]
**Use case:**
When starting two streams, one for EXG channels and one for Aux channels the output CSV files are not time synced. They are off by a couple samples.

**Describe the solution you'd like:**
It would be nice if start_stream and add_steamer were auto synced if called at the same time.

**Comment by Andrey1994** [comment]
Its impossible in generic case because these packages can be received from device in different time moments and may have different sampling rates

Also you can do some timestamp matching in user code

**Comment by Andrey1994** [comment]
Also, add_streamer doesnt actually starts the stream and you can call it even before start_stream method
