### ISSUE TITLE
C# examples can't find DataHandler.dll

### ISSUE THREAD

**Issue by zombers** [brainflow-dev/brainflow#573]
when i run the code "DataFilter.perform_lowpass()" 
it show me this:
System.DllNotFoundException:“Unable to load DLL 'DataHandler.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)”

**Comment by Andrey1994** [comment]
If you build c# code by yourself then you need to compile c++ part and set PATH env variable to point to c++ dlls(check docs)

If you are using nuget, there are precompiled libs inside and they are unpacked automatically. Need to check the folder for unpacking and copypaste them to current dir or set PATH env var
