### ISSUE TITLE
Migrate to .NET Standard

### ISSUE THREAD

**Issue by javidsho** [brainflow-dev/brainflow#578]
**Use case:**
.NET Framework is deprecated and almost nobody uses it for new projects. Since most people either use .NET Core/.NET, this will result in package incompatibility and warnings when included in a project.

**Describe the solution you'd like:**
I'd really like cross-platform packages based on .NET Standard 2.0 - which is the most compatible of all, and that includes Unity. Even if it's Windows-only, it can still be a modern package.

**Describe alternatives you've considered:**
I'm currently referencing the package and getting the warning. I'm still able to use brainflow, but I cannot use some packages due to incompatibility with .NET Standard such as logging!

**Comment by Andrey1994** [comment]
Hi!

Could you send a PR with required changes and I will take a look and test? As far as I understand it should be a small fix

**Comment by javidsho** [comment]
Hi there! Sure I'll do it when I have time

**Comment by Andrey1994** [comment]
for others as a reference: https://code-maze.com/differences-between-net-framework-net-core-and-net-standard/

**Comment by Andrey1994** [comment]
https://www.michaeltaylorp3.net/porting-a-net-framework-library-to-net-standard/
