### ISSUE TITLE
Cannot Connect to Ganglion With Native BLE

### ISSUE THREAD

**Issue by mgroth0** [brainflow-dev/brainflow#584]
I have followed the code in https://github.com/brainflow-dev/brainflow/pull/574/commits/5414c39624c32aa78b1c749621b5bc2a2341f4e4

Basically, the only thing I changed in my previous code is that I removed the line that set the value of `BoardShim.serial_port` and I switched `GANGLION_BOARD` to `GANGLION_NATIVE_BOARD`.

When I try to stream, I get a `BOARD_NOT_CREATED_ERROR`

**Comment by Andrey1994** [comment]
share the logger output

**Comment by Andrey1994** [comment]
I cannot reproduce it, follow these steps to run with gdb: https://brainflow.readthedocs.io/en/stable/BrainFlowDev.html#debug-brainflow-s-errors

To build locally you will need `python tools\build.py --ble --debug`
Inside gdb session you will need to type `r` and `bt` after error.
And share gdb output

**Comment by Andrey1994** [comment]
could you tell which macos version it is and which cpu(arm intel)?
