### ISSUE TITLE
Consider Moving User APIs to Separate Page for each Language

### ISSUE THREAD

**Issue by stellarpower** [brainflow-dev/brainflow#594]
Hi,

It's a difficult when I am using the search feature in my browser, whilst looking around on the User API page for me. This is because the documentation for multiple different languages are present on the same page. So if I Ctrl+f search for e.g. `BoardShim`, I get mixed results form the C++ API, The Python API, the Matlab API, etc. which is a bit inconvenient.

I think most users are likely to be concentrating on one language at a time, so I feel like each language would probably be better on its own page. The navigation bar at the side also seems to give me the impression that each is on a separate page, given the way the colours are different; but if I scroll far enough I realise they're not:
![image](https://user-images.githubusercontent.com/5004545/212477850-7f206470-fb3a-447d-8007-9a85d5b39164.png)

Thanks

**Comment by Andrey1994** [comment]
I've tried to do it but it leads to some bad side effects like not consistent sidebar behavior, etc in sphinx read the docs theme
