### ISSUE TITLE
C# GetRow method is inefficient

### ISSUE THREAD

**Issue by philippitts** [brainflow-dev/brainflow#613]
**Describe the bug**
The `MatrixHelpers::GetRow` method performs a copy from the buffer returned by `get_current_board_data()`. This copy requires a new memory allocation on each call. In real-time applications (e.g. driven by Unity) `GetRow` can be called very frequently in order to process new data coming into the buffer. This causes large garbage collection spikes that have significant performance impacts.

**To Reproduce**
Create a Unity project, create a new script, and add that script to the scene. In the script use:
```
private BoardShim board;

private void Awake()
{
    var parameters = new BrainFlowInputParams { serial_port = SerialPort };
    board = new BoardShim((int)BoardIds.CYTON_BOARD, parameters);
}

private void Update()
{
    var buffer = board.get_current_board_data(512);
    var channel = StandardBuffer.GetRow(0);
}
```

**Info (please complete the following information):**
 - Board ID: 0 (although it doesn't really matter)
 - Windows 10
 - C# .NET Standard 2.0
 - x64

Using commit [df6657d](https://github.com/brainflow-dev/brainflow/commit/df6657d7cbe65328cd88267d82013e7493f46dcc) in order to take advantage of https://github.com/brainflow-dev/brainflow/pull/609.

**Expected behavior**
There should not be significant garbage collection spikes.

**Screenshots**
![image](https://user-images.githubusercontent.com/84428015/225073482-b33af79d-e270-409f-9334-68ef599851ac.png)

**Comment by Andrey1994** [comment]
I know but idk how to get a pointer to the row in 2d array in c#
