### ISSUE TITLE
[MATLAB]error message

### ISSUE THREAD

**Issue by myu122241** [brainflow-dev/brainflow#682]
Good afternoon.
I am starting with Brainflow on Matlab. When I test the sample code [Matlab Get Data from a Board] , I always get an error message in the brainflow log:

[board_logger] [error] Board with id -1 and the same config already exists

What does it mean and how could I solve it?
Thank you!

**Comment by Andrey1994** [comment]
Hi, it means that you didnt call release_session after successfull prepare_session
