### ISSUE TITLE
Add support for dual OpenBCI cyton+daisy boards (for one brain + one computer)

### ISSUE THREAD

**Issue by soulsyrup** [brainflow-dev/brainflow#691]
**Use case:**
I would like to connect two pairs of cyton+daisy OpenBCI boards to a computer, using BrainFlow

**Describe the solution you'd like:**
Ability for BrainFlow to get the data (of both cyton+daisy boards as one set of signals) and send it out like it does with other hardware

**Comment by Andrey1994** [comment]
hi, you can create two instances of BoardShim class and get data from both simultaneously. In terms of multiboard support it should be enough for all cases, if you want you can stack data later on how you want.

**Comment by Andrey1994** [comment]
https://github.com/brainflow-dev/brainflow/blob/master/python_package/examples/tests/brainflow_multiboard_get_data.py smth like this
