### ISSUE TITLE
Consider adding brainflow to NITRC

### ISSUE THREAD

**Issue by arnodelorme** [brainflow-dev/brainflow#698]
NITRC references all the neuroscience tools used in Research. NITRC is a non-profit NIH-sponsored website. This will help increase your tool (and associated paper) visibility.

https://www.nitrc.org/

**Comment by Andrey1994** [comment]
hi, thanks for this idea, simple promotion opportunities are more than welcome. submitted the form for adding

**Comment by arnodelorme** [comment]
Thanks.
