### ISSUE TITLE
Accelerometer and gyroscope data stream for GforcePro Oymotion Armband 

### ISSUE THREAD

**Issue by zubaidah93** [brainflow-dev/brainflow#703]
**Use case:**
A clear and concise description of what the problem is and why do you need this feature

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Comment by Andrey1994** [comment]
We dont parse it currently, I will need to check if its available together with the EMG data. If there are no conflicts in sampling rates, etc, we can add it

**Comment by Andrey1994** [comment]
[temp.patch](https://github.com/brainflow-dev/brainflow/files/14077636/temp.patch)


I cannot make it work together with emg data, as soon as I enable accel and gyro data on gforceSDKCXX level I stop getting valid emg from the board, temp git diff is attached, so you can patch it a little bit locally depending on your own needs.

I also see that in gforceSDKCXX examples accel and gyro data are off, so maybe there was a reason for it. I would recommend you to ask oymotion guys for more info
