### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by Pandapip1** [brainflow-dev/brainflow#718]
**Use case:**

I'm packaging up brainflow for the nix package manager, and am unable to build the latest version (5.12.1) due to https://github.com/brainflow-dev/brainflow/pull/712 not being present.

**Describe the solution you'd like:**

Please publish a new release that successfully builds.

**Describe alternatives you've considered:**

For the time being, I'll point the build at `master`.

**Comment by Andrey1994** [comment]
hi, will do, in the meantime you are welcome to create a PR with nix package for brainflow.

**Comment by Pandapip1** [comment]
> in the meantime you are welcome to create a PR with nix package for brainflow.

I'm actually upstreaming this to [nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by Andrey1994** [comment]
I want to add #716 to the new release, as soon as its done, will create a new one

**Comment by Pandapip1** [comment]
Fair enough!
