### ISSUE TITLE
.jar files

### ISSUE THREAD

**Issue by fafapv** [brainflow-dev/brainflow#72]
Hi,
I just have a quick question about the difference between the two Java .jar files available. What is the difference between the one with and the one without dependencies?
Thanks

**Comment by Andrey1994** [comment]
jar with dependencies created using this Maven plugin https://maven.apache.org/plugins/maven-assembly-plugin/
BrainFlow Java package has a few dependencies like JNA to call C++ code, common-lang, gson, etc. In jar with dependencies all of them are available so its like standalone jar file with everthing included.

In apps I usually use jar with dependencies, but if you already have JNA or smth else as a dependency using this jar file may lead to version conflict
