### ISSUE TITLE
Upload brainflow rust bindings to crates.io

### ISSUE THREAD

**Issue by Pandapip1** [brainflow-dev/brainflow#721]
**Use case:**

I'd like to use brainflow in a rust project, and https://crates.io/ is the standard way of distributing Rust packages.

**Describe the solution you'd like:**

Brainflow should be uploaded to https://crates.io/

**Describe alternatives you've considered:**

*N.A.*

**Comment by Andrey1994** [comment]
hi, there is one problem I cannot solve with crates. BrainFlow uses C\C++ dyn libs in all bindings and crates does not allow to package binary files properly, there is a strict limitation for max size of the package.
idk how other projects bypass it

**Comment by Pandapip1** [comment]
> hi, there is one problem I cannot solve with crates. BrainFlow uses C\C++ dyn libs in all bindings and crates does not allow to package binary files properly, there is a strict limitation for max size of the package.

My understanding is that crates just assume that the user has the libraries installed.

**Comment by Andrey1994** [comment]
but in that case users still need to download libraries from somewhere and set LD_LIBRARY_PATH or PATH manually. Then advantage of using crates only for Rust code is debatable

**Comment by retiutut** [comment]
It does seem to be the official package distribution for Rust https://github.com/rust-lang/crates.io.

**Comment by Pandapip1** [comment]
Was this closed accidentally, or is this actually not planned. If so, would you mind just providing a short explanation for the wontfix, since all your previous concerns have been addressed?

**Comment by Andrey1994** [comment]
Wont fix, I dont see much value uploading rust part only wo compiled libs, they still should be copied manually. And afik there is still file size limit.
So until there is no more or less acceptable way to bundle C libs with rust part we will not upload it
