### ISSUE TITLE
brainflow.exit_codes.BrainFlowError: BOARD_WRITE_ERROR:4 unable to prepare streaming session

### ISSUE THREAD

**Issue by NewBiee777** [brainflow-dev/brainflow#726]
Hello !
I just started to test Brainflow Python API.
Trying to run the get data from board with my Cyton and its WiFi shield.
See the results.
Am I missing something?
Thanks a lot !
![2002b0b9dd548c5143e2e9316676a1a](https://github.com/brainflow-dev/brainflow/assets/161293515/cc6a87ae-87c9-4937-b93e-432fccdeba0b)
![2aa9559e8f34fc8971beea529108837](https://github.com/brainflow-dev/brainflow/assets/161293515/1ae94ef7-5cbe-40a1-8824-8e768bb6f80e)

**Comment by Andrey1994** [comment]
Hi! How do you run it? I dont understand why local ip and default iü from argparse are in different nets..

**Comment by Andrey1994** [comment]
And what is the full output from the dev logger?

**Comment by NewBiee777** [comment]
> And what is the full output from the dev logger?
This is the complete logger
![image](https://github.com/brainflow-dev/brainflow/assets/161293515/b3c3510f-2d65-43c0-a4ad-9296bea9190a)

**Comment by Andrey1994** [comment]
Can you show the full json on top?

**Comment by NewBiee777** [comment]
You mean the full list of outputs?
![image](https://github.com/brainflow-dev/brainflow/assets/161293515/09a76e01-838c-49b3-bc45-eb0a0f5282cb)

**Comment by Andrey1994** [comment]
how your network is configured? your pc connected to the net from wifi shield, right?

**Comment by Andrey1994** [comment]
can you share the output of `ipconfig.exe` executed in the console?
