### ISSUE TITLE
WASM build and support for browsers

### ISSUE THREAD

**Issue by mpbb** [brainflow-dev/brainflow#734]
The existence of WebUSB and Web Serial make in browser data collection a viable platform for brainflow.

Can we explore compiling to wasm and perhaps packaging for web?

**Comment by Andrey1994** [comment]
I think, I built it for web assembly before. Signal processing part and synthetic board worked fine, but all IO boards were broken. None of the actual boards worked for me from the box and I even not sure that its possible.
No idea how web serial works and not an expert in web...
Would be good if you take the lead on that and help with porting to wasm

**Comment by Andrey1994** [comment]
DataFilter part should work, I dont remember how I built it, but more likely smth like this https://peterdn.com/post/2020/12/31/building-c-and-cpp-libraries-for-webassembly/

Its a normal Cmake project, so should be straightforward

**Comment by Andrey1994** [comment]
closing as non planned, it should be possible to build it for webassembly but its probably not one of the builds we are going to create ourselves. If there are any issues with it feel free to create new ones
