### ISSUE TITLE
Data not appearing at sampling rate

### ISSUE THREAD

**Issue by fafapv** [brainflow-dev/brainflow#81]
Hi,
I am using a cyton + daisy serial setup and a custom java program. I am running into an issue where data only appears in the ring buffer in large chunks every half a second. Is there a way to get data to appear at the board's sampling rate of 125 Hz or every 8 milliseconds?
Thanks

**Comment by Andrey1994** [comment]
Hi.

Did you see this https://docs.openbci.com/docs/10Troubleshooting/FTDI_Fix_Windows ? 
There are similar guides for other OSes.

**Comment by Andrey1994** [comment]
It will not ensure exactly 8ms but data stream will be much smoother

**Comment by fafapv** [comment]
Runs much smoother now! Thanks a ton!
