### ISSUE TITLE
Cyton Daisy WiFi only streams 8 channels

### ISSUE THREAD

**Issue by nateGeorge** [brainflow-dev/brainflow#90]
When streaming from the OpenBCI Cyton Daisy WiFi setup, I only get 8 channels of data (1-8).  Channels 9-16 are all 0s.  There was a similar issue in the OpenBCI GUI I reported (https://github.com/OpenBCI/OpenBCI_GUI/issues/837).  Here is the code I used to collect data:

```python
import pandas as pd
from brainflow.board_shim import BoardShim, BrainFlowInputParams

params = BrainFlowInputParams()
# default IP when connecting to board directly
params.ip_address = '192.168.4.1'
params.ip_port = 6227  # random port that was available
board = BoardShim(6, params)

board.prepare_session()
board.start_stream()

# other code is in here for collecting data
time.sleep(3)
data = board.get_board_data() # get all data and remove it from internal buffer
board.stop_stream()
board.release_session()

df = pd.DataFrame(data.T)
df.drop([0] + list(range(20, 30)), inplace=True, axis=1)
df.to_csv('test_data.csv', index=False)
```

If you examine the channels 1-8, they are fine, but channels 9-16 are all 0s.

I was using version 3.4.1 on Ubuntu.  I don't have the headset for a week or two so can't test the latest versions that were released, but it didn't look like anything was committed to the code that would fix this problem.

**Comment by Andrey1994** [comment]
I am pretty sure its not an issue in code. Did you check your hardware setup?

**Comment by nateGeorge** [comment]
Yes, before collecting data I tested that all channels were working in the GUI.  I know I've gotten wifi data working on all channels, but it was connecting directly to the board not using brainflow.

**Comment by nateGeorge** [comment]
I will have to test again when I can, possibly next Wednesday, but if not, it may not be until a week or so later.

**Comment by Andrey1994** [comment]
Which gui version did you use?

**Comment by nateGeorge** [comment]
5.0.0 I believe.  It looks like actually the fixes were implemented in between 3.4.1 and the latest release, so I'll have to recollect the data with the latest version.  https://github.com/brainflow-dev/brainflow/commit/e564a2469f55939bea562434dca74a2de8332587

**Comment by nateGeorge** [comment]
I think when I collected the data, 3.4.2 wasn't out yet and I didn't notice the data quality issue until just today.

**Comment by Andrey1994** [comment]
GUI 5.0.0 uses brainflow and provides exactly the same data, so it should work

**Comment by nateGeorge** [comment]
Yes, but I was using the brainflow API not the GUI to collect data.  Anyway, I noticed another issue with missing data from the API I'll post later probably (need to confirm it doesn't happen in the GUI).

**Comment by Andrey1994** [comment]
GUI uses brainflow API and returned data is exactly the same everywhere.... in fact GUI runs exactly the same code as python scripts
