### ISSUE TITLE
_CtrlsValidHeapPointer(block)

### ISSUE THREAD

**Issue by nosa999** [brainflow-dev/brainflow#94]
Hi ,
I have following error on when I click stop streamer on openBCI_GUI.
![image](https://user-images.githubusercontent.com/40929193/95331291-a4fc4b80-08b6-11eb-87d8-612ccc5d752d.png)

**Comment by Andrey1994** [comment]
its not an issue in brainflow upstream code, its a bug(wip stage) in your fork.
closing it here
